apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - metadata.yaml
  - silo.yaml
images:
  - name: ghcr.io/nishanttyagi28/pgrestoredrill
    newName: pgrestoredrill
    newTag: kind
patches:
  - path: secret.yaml
  - path: drill.yaml
  - path: pull-api.yaml
  - path: pull-migrate.yaml
  - path: pull-drill.yaml
